### ISSUE TITLE
Multidimensional parameters and the annotation model

### ISSUE THREAD

**Issue by Dashadower** [bbbales2/regressions#34]
Looking at the [annotation model](https://aclanthology.org/Q14-1025.pdf), first thing that needs to be added are multidimensional parameters. I've thought about how we _might_ try to make it work with the current subscripts without adding new syntax for declaring dimensions. Or we can completely separate subscripts and dimensions syntax-wise.
```
       item  annotator  rating
0         1          1       6
1         2          1       3
2         3          1       1
3         4          1       3
4         5          1       1
```
(this is the the first 5 lines of the annotation model's data)

## Option 1

The max rating value is 6. So if we wanted to create a vector of length 6 for subscript `[item, annotator]`, we _might_ allow expressions to represent dimensions, so something like `my_vector[item, annotator, 6]`. This would mean, "create a parameter of length 6, for each item-annotator pair". If we do use this format, subscript/dimension evaluation will be modified to check whether the tokens inside the brackets are Identifiers or an expression.

But then this messes with the current subscript evaluation order. Say we modified the skill model a bit and wanted to model home vs away performance(assume all teams played both as home and team):
```
score_diff~normal(skills[home_team, year, 1]-skills[away_team, year, 2],sigma);
skills[team, year, 2] ~ normal(skills_mu[year], tau);
skills_mu[year] ~ normal(0.0, 1.0);
tau<lower=0.0> ~ normal(0.0, 1.0);
sigma<lower=0.0> ~ normal(0.0, 10.0);
```
In the old model, all we needed was the first line to evaluate where the subscripts come from. But now, we also need to check cases where skills is on the lhs of a statement to find its declared dimension(2). Of course, dimensions are independent of subscript evaluation; we might treat them completely separately and maybe it won't become that big of a problem.

For functions/distributions that receive vectors as arguments, we can try and adopt's numpy's `:` syntax, which should return the entire dimension: `categorical(vector_param[subscript_1, :])`

## Option 2
We separate subscript and dimensions syntactically. One way of doing it might be defining subscripts with braces, and dimensions with brackets: `skills{team, year}[2]`. So accessing variables would also change: `skills{home_team, year}[1]` or `skills{away_team, year}[2]`

## compatibility with pandas and complications
How are we going to handle multidimensional columns cleanly on a pandas dataframe? Are we going to try stan's approach which unpacks them into index scalar variables? e.g.`arr[5, 4] -> arr__1_1, arr__1_2, ... , arr__5_4`.

Additionally, are we going to rely on the generated python code throwing errors instead of checking during compile-time that dimensions match for operations?

## Conclusion

I'm not exactly certain if there's a syntactically clean way to define subscripted and indexed variables. I'm curious if you have other ideas. But if given the option, I wish to opt for the ease of model writing/most natural format, which is the reason I think option 2 is kinda meh.

**Comment by bbbales2** [comment]
> something like my_vector[item, annotator, 6]. This would mean, "create a parameter of length 6, for each item-annotator pair"

Right now we're letting the parameter use define the shapes. I think we should keep leaning on that.

So if we wanted my_vector[item, annotator] to be a vector of length 6 -- then somehow we need to use it as if it is a length 6 vector and the program infers the shape.

Using the syntax for data from the paper (Figure 2), lets say we have the dataframe:
```
ii,  jj,  y
1,    1,  4
1,    3,  1
192, 17,  5
```

The Bayes rule stuff here is structure like:
```
p(theta, z | y) = p(y | z, theta) p(z) p(theta) / p(y) = p(y, z, theta) / p(y)
```

We can't sample that discrete parameter z, so we'll need to integrate it out. We can do that by summing over all possible values of z:
```
p(theta | y) = \sum_z p(y, z, theta) / p(y)
```

p(y, z, theta) is a product of a lot of terms, and z is technically all combinations of potential labels. So if we had I = 1000 (that's a capital I -- using the notation in the paper) and K = 7 (number of different possible responses), that'd be 7^1000 p(y, z, theta) terms we'd need to sum over.

What happens to simplify this is that p(y, z, theta) factors over each item, and within each item there is only one discrete variable. So like:

```
p(y, z, theta) = \prod_i p_i(y, z, theta)
\sum_z p(y, z, theta) = \prod_i \sum_z_i p_i(y, z_i, theta)
```

So it's now a product of I terms, each of which is a sum of K terms. It's weird to see that sum go inside the product (and I hope I haven't made a syntax error here) -- the easier way to derive this is integrating out one latent z at a time (so if you have I items, then write down p(y, z_{-i}, theta) where the z_{-1} means you've integrated only one of the elements of z out).

p_i(y, z_i, theta) itself is a product of things though (because multiple annotators can label the same item).

So assuming n indexes these responses:
```
p_i(y, z_i, theta) = \prod_n p_i(y_n, z_i, theta)
```

Alright and last thing, because of how the categorical distribution works:

```
p_i(y | z_i, theta) = theta[j[n], y, z_i]
```

where j here indexes the annotator.

I don't know quite how to order this computation in rat, but I think if we expand the dataframe to include the z_i variables we want to integrate over, this can be expressed pretty clearly as three groupby + aggregates.

Assuming K = 7, the dataframe from above would be:
```
ii,  jj,  y, z
1,    1,  4, 1
1,    1,  4, 2
1,    1,  4, 3
1,    1,  4, 4
1,    1,  4, 5
1,    1,  4, 6
1,    1,  4, 7
1,    3,  1, 1
1,    3,  1, 2
1,    3,  1, 3
1,    3,  1, 4
1,    3,  1, 5
1,    3,  1, 6
1,    3,  1, 7
192, 17,  5, 1
192, 17,  5, 2
192, 17,  5, 3
192, 17,  5, 4
192, 17,  5, 5
192, 17,  5, 6
192, 17,  5, 7
```

This explode thing can be thought of as outer join or Kronecker product -- could probably be embedded in syntax instead of actually copying the dataframe 5 times but for the example let's just copy

So like:
```
groupby ii, z; let lp1 be the sum of log(theta[jj, y, z])
groupby ii; let lp2 be the log_sum_exp of lp1
let lp3 be the sum of lp2 # no grouping on the last line -- summing over everything to get the final log density increment
```
