### ISSUE TITLE
Use of unassigned variable on right hand side

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#44]
This model doesn't work (I was trying to define a non-centered parameterization and accidentally wrote it):

```python
df = pandas.DataFrame({ "abortion" : [0], "state" : [1] })

model_string = """
abortion ~ bernoulli_logit(a_state[state]);
a_state[state] = a_state[state];
"""

model = Model(df, model_string=model_string)
```

Error looks like:
```
 return {self.line.rhs.code()}"])
  File "/home/bbales2/regressions/rat/ops.py", line 104, in code
    variable_code = self.variable.code()
AttributeError: 'NoneType' object has no attribute 'code'
```

**Comment by Dashadower** [comment]
Compiler assumes all variables on RHS are known at evaluation time. We would need a default prior like for #43 and in addition require changes to the dependency graph generation, since we now need ordering between lines that share the same variable on the LHS. e.x. `a_param[group] ~ normal(0, 1.0);` should be evaluated before `a_param[group] = a_param[group] * 2;`

**Comment by bbbales2** [comment]
I agree this should just be an error -- no need to support the syntax here -- just meant to say the error was confusing in figuring out what was happening.

**Comment by bbbales2** [comment]
This is fixed. Error is now:

```
rat.exceptions.CompileError: An error occurred while compiling the following line(2:18):
a_state[state]' = a_state[state];
                  ^
Exactly one (no more, no less) subscripts can be shifted in a recursively assigned variable
```

It's a correct error though I probably could have worded it a bit clearer lol.
